[MasterConfig]
Logfile = "/path/to/log/file"

[[PluginConfig]]
Name = "plugin"
Path = "/path/to/plugin"
Args = ["-config", "/path/to/config-file"]

[[LoggerConfig]]
Name = "logger"
Path = "/path/to/logger"
